name: Java CI with Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Runs at 2:00 AM UTC every day (daily build)
    - cron: '0 2 * * *'
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: ./mvnw clean package
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jakartaee-hello-world
        path: target/jakartaee-hello-world.war
